name: Build
on:
  push:
    branches: ["master"]
    paths:
      - "docker-compose.yml"
      - "docker/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["master"]
    paths:
      - "docker-compose.yml"
      - "docker/**"
      - ".github/workflows/**"

env:
  REGISTRY: ghcr.io
  LATEST_TAG: ghcr.io/rootshell-coder/proftpd:latest
  TRIVY_SECURITY: SECURITY.txt

jobs:
  build:
    name: Publish to github registry
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.LATEST_TAG }}

  check:
    needs: [build]
    name: Check Trivy
    runs-on: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - name: Check Trivy
        run: |
          docker pull ${{ env.LATEST_TAG }}
          docker run --rm ghcr.io/rootshell-coder/trivy-cached:latest image ${{ env.LATEST_TAG }} --skip-db-update > ${{ env.TRIVY_SECURITY }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: RootShell-coder
          author_email: Root.Shelling@gmail.com
          message: "trivy"
          add: "*.txt"
